# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FairBusinessPractices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('office_id', models.IntegerField(primary_key=True, serialize=False)),
                ('office_desc', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state_code', models.CharField(blank=True, max_length=2, null=True)),
                ('zip_code', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'offices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('comments', models.CharField(blank=True, max_length=255, null=True)),
                ('is_verified', models.IntegerField()),
                ('created_ts', models.DateTimeField()),
                ('updated_ts', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'patients',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('violation_id', models.IntegerField(primary_key=True, serialize=False)),
                ('violation_desc', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'violations',
                'managed': False,
            },
        ),
    ]
